---
- name: Download and install amazon-ssm-agent rpm package
  dnf:
    # The amazon-ssm-agent RPM is currently unsigned:
    # https://github.com/aws/amazon-ssm-agent/issues/235
    disable_gpg_check: yes
    name: "{{ package_url }}"
