---
# tasks file for amazon-ssm-agent

- name: Load var file with package names based on the OS type
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "{{ role_path }}/vars"

- name: Load tasks file with install tasks based on the OS type
  include: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - install_{{ ansible_distribution }}_{{ ansible_distribution_release }}.yml
        - install_{{ ansible_distribution }}.yml
        - install_{{ ansible_os_family }}.yml
      paths:
        - "{{ role_path }}/tasks"

- name: Enable Amazon SSM Agent service
  service:
    name: amazon-ssm-agent
    enabled: yes
